import type { ActId } from './palette';

/**
 * `icon` is UI art: it lives on the offer cards' ink surface, so CHECK judges
 * it against ink and the enemy value ceiling does not apply — a card-only icon
 * may wear paper, which on the field is the player's alone. An icon marked
 * `fieldRiding` is also drawn on the field (G-036) and may not (law 10).
 */
export type AssetRole = 'player' | 'swarm' | 'boss' | 'pickup' | 'icon';

export interface AssetSpec {
  /** Filename stem. Also the key in the packed atlas. */
  id: string;
  /** Human name, as it would appear in the enemy data file. */
  name: string;
  act: ActId;
  role: AssetRole;
  /**
   * The subject half of the prompt. The style half is appended by the
   * pipeline and is identical for every asset — consistency is not the
   * prompt's job (D-005).
   */
  subject: string;
  /**
   * One sentence, required of every enemy before it ships (PLAN.md
   * mechanism 2). A "flying skull" cannot answer it; a "substitute teacher
   * who does not know your name" can. Written to be lifted verbatim into the
   * enemy data file.
   */
  whyThisStage?: string;
  /** What the asset is testing. Test batch only. */
  tests?: string;
  /**
   * Law 4 override (G-013). Ruled geometry characterises one object rather
   * than styling a whole act, so it is declared per asset. Omit for the act's
   * default, which is hand-cut everywhere.
   */
  geometry?: 'hand-cut' | 'ruled';
  /** Base seed. Rejections mutate it rather than escalating to a human. */
  seed: number;
  /** Longest side of the finished sprite — the act's scale grid. */
  targetSize: number;
  /**
   * Where the pixels come from (G-038). Omitted: generated by fal through
   * `art:batch`. `'svg'`: authored by hand at `tools/art/svg/<act>/<id>.svg`
   * and rasterised by `art:svg`. Either way the result goes through the same
   * CONFORM and CHECK, and law 11 and D-007 gate it the same way. For an svg
   * asset `subject` is the written description, never sent anywhere — the
   * content rule still runs on it.
   */
  source?: 'svg';
  /**
   * Icons only. This icon is also drawn on the field — a shot, an orbiter, a
   * stamp, a rider (G-036) — so besides the card checks it keeps off the
   * field's reserved colours: every threat colour (threats), paper (the
   * player) and every act's light tone (pickups), law 10 — in every act,
   * because items are not act-scoped. Omitted: card-only, judged against the
   * card surface alone (G-035).
   */
  fieldRiding?: true;
}

export interface GenerationRecord {
  assetId: string;
  model: string;
  seed: number;
  prompt: string;
  styleSuffix: string;
  attempt: number;
  rejected: Array<{ seed: number; failures: string[] }>;
  checks: Array<{ name: string; pass: boolean; measured: number; expected: string }>;
  generatedAt: string;
}
